# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_detectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DetectImage',
        ),
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cctv.Camera'),
        ),
    ]
