# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0006_auto_20180913_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_info',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
