# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0007_camera_camera_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detection_type',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
