# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0008_image_detection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cctv.Camera', to_field='camera_id'),
        ),
    ]
