# Generated by Django 2.1 on 2018-09-14 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0011_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='camera',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
