# Generated by Django 2.1 on 2018-09-14 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0012_auto_20180914_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('camera', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cctv.Camera', to_field='camera_id')),
            ],
        ),
    ]
